name: tennis_match_pro
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.1
  firebase_storage: ^12.4.10
  google_sign_in: ^6.2.1
  geolocator: ^11.0.0
  google_maps_flutter: ^2.6.1
  url_launcher: ^6.2.1
  image_picker: ^1.1.2
  http: ^1.1.0
  shared_preferences: ^2.2.3
  async: ^2.11.0
  # Internationalization and formatting dependency
  intl: ^0.18.1
  google_fonts: ^6.2.1
  image_cropper: ^11.0.0 # Actualizado a la última versión
  share_plus: ^7.0.0
  path_provider: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/courts/
