// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNN7N7QepG-5-imUgzEXUmUsWUCe7mIkM',
    appId: '1:731751678168:web:ea9e6787c01ef7df61d7ad',
    messagingSenderId: '731751678168',
    projectId: 'tennis-match-pro',
    authDomain: 'tennis-match-pro.firebaseapp.com',
    storageBucket: 'tennis-match-pro.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7XDnhSKSWCPFk6oBdX8Wv-d6jeOiGiI4',
    appId: '1:731751678168:android:996d9ef0856f1fbd61d7ad',
    messagingSenderId: '731751678168',
    projectId: 'tennis-match-pro',
    storageBucket: 'tennis-match-pro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMJTcnS2W6uC8-VzzNKBWq_KFr20J5MGQ',
    appId: '1:731751678168:ios:760a0d292ef0a4ec61d7ad',
    messagingSenderId: '731751678168',
    projectId: 'tennis-match-pro',
    storageBucket: 'tennis-match-pro.firebasestorage.app',
    iosBundleId: 'com.mathiewman.tennis.tennisMatchPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMJTcnS2W6uC8-VzzNKBWq_KFr20J5MGQ',
    appId: '1:731751678168:ios:760a0d292ef0a4ec61d7ad',
    messagingSenderId: '731751678168',
    projectId: 'tennis-match-pro',
    storageBucket: 'tennis-match-pro.firebasestorage.app',
    iosBundleId: 'com.mathiewman.tennis.tennisMatchPro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNN7N7QepG-5-imUgzEXUmUsWUCe7mIkM',
    appId: '1:731751678168:web:b03a7b49b411dbfb61d7ad',
    messagingSenderId: '731751678168',
    projectId: 'tennis-match-pro',
    authDomain: 'tennis-match-pro.firebaseapp.com',
    storageBucket: 'tennis-match-pro.firebasestorage.app',
  );
}
